name: vectopt
channels:
- conda-forge
- pytorch
- gpytorch
dependencies:
- python>=3.10
- gpytorch
- botorch>=0.10.0,<0.12.0
- cvxpy
- scikit-learn
- scipy
- matplotlib
- numpy
- jupyter
- pytest
- pytest-cov
- flake8
- flake8-print
- pydocstyle
- black
- bandit
- sphinx_rtd_theme
- pip:
    - -r docs/requirements.txt
